--Helvault backup -> Archidekt CSV import
SELECT
  COUNT() AS COUNT,
	ZFACENAME,
  ZPARSEDSETCODE,
  CASE ZPARSEDLANGUAGE
   WHEN 'ph' THEN 'en'
   WHEN 'ja' THEN 'jp'
   ELSE ZPARSEDLANGUAGE
   END AS LANGUAGE,
  ZSCRYFALLID,
  CASE ZPARSEDEXTRAS
   WHEN 'foil' THEN 'Foil'
   WHEN 'etchedFoil' THEN 'Foil'
   ELSE 'Normal'
   END AS VARIANT
FROM ZPERSISTEDMTGCARD
GROUP BY ZSCRYFALLID
ORDER BY ZFACENAME, ZSCRYFALLID
